### ISSUE TITLE
Migrate CI to GitHub actions (or elsewhere)

### ISSUE THREAD

**Issue by larsgw** [statrs-dev/statrs#130]
I believe the CI has not been running on Travis-CI since a while¹, as it has been shutting down for open source projects ([and it did not catch this two weeks ago](https://github.com/boxtown/statrs/pull/129)). I could try to migrate it the testing to GitHub actions.

¹ Edit: it has been running, but it has not been reporting the CI results back to GitHub it seems.

**Comment by vks** [comment]
It seems like our CI is now not running anymore.

**Comment by larsgw** [comment]
I can see if I can work on a GitHub Actions workflow, if that helps.
