### ISSUE TITLE
Allow vector of floats for mean in statsrs::distribution::Normal (as per numpy.random.normal)

### ISSUE THREAD

**Issue by j-griffiths** [statrs-dev/statrs#131]
The code below understandably runs into a type mismatch as the argument `mean` of statsrs::distribution::Normal requires a `f64`.

[Similar to `np.random.normal` in Python's numpy package](https://numpy.org/doc/stable/reference/random/generated/numpy.random.normal.html), it would be good to add support for Vector arguments of `mean` in statsrs.

Rust code (doesn't work due to type mismatch in `let n...`)
```
let x0: Vec<f64> = thread_rng().sample_iter(Standard).take(200).collect();

let endpoint_mean: Vec<_> = x0
  .iter()
  .map(|&x| x * (-0.5).exp())
  .collect();

let endpoint_variance: f64 =
  (SIGMA.pow(2) as f64 /  (1.0 - (-1.0).exp())).sqrt();

// this should output a vector n of some arbitrary length (here, 200). the argument endpoint_mean could be a Vec<f64> (as per numpy), but currently must be f64.
let n = Normal::new(endpoint_mean, endpoint_variance).unwrap();
```

Python code (works with an array of floats)
```
x0 = np.random.normal(loc = 0, scale = 1, size = 10000) // initial points, outputs a 10_000 vector
mean = X0*np.exp(-0.5) // 10_000 vector 
variance = np.sqrt(4/(1-np.exp(-1)) // = 1.5901201952413002
xt = np.random.normal(m,v) // = 10_000 vector
```

**Comment by vks** [comment]
I'm not sure that this is in the scope of `statrs`, because in general this will depend on some array and possibly linear algebra crate. Shouldn't this functionality rather be provided by the array/linear algebra crates? Note that `random` (from the Python standard library) does not provide this either, you have to use the array library `numpy` instead.

Does the [`ndarray-rand` crate](https://crates.io/crates/ndarray-rand) provide what you want?

**Comment by troublescooter** [comment]
Is there a reason `map` is not the preferred way to accomplish this?
Alternatively, there's `MultivariateNormal` which has a constructor that allows multidimenstional arguments.

**Comment by j-griffiths** [comment]
> Is there a reason `map` is not the preferred way to accomplish this?
> Alternatively, there's `MultivariateNormal` which has a constructor that allows multidimenstional arguments.

Apologies if this is going out of the scope of GitHub issues, but how would `map` work in this scenario? (To clarify, I start with an initial, random normal distribution of points, I take the mean and variance of the endpoint of an Ornstein-Uhlenbeck process, and calculate the random, normal distribution of endpoints from that).

`MultivariateNormal` seems promising, although I have a scalar variance and that crate requires a (co)variance matrix (perhaps this should just be a diagonal matrix?). I'll explore this crate further.



> I'm not sure that this is in the scope of `statrs`, because in general this will depend on some array and possibly linear algebra crate. Shouldn't this functionality rather be provided by the array/linear algebra crates? Note that `random` (from the Python standard library) does not provide this either, you have to use the array library `numpy` instead.
> 
> Does the [`ndarray-rand` crate](https://crates.io/crates/ndarray-rand) provide what you want?

Thanks for the suggestion, but `ndarray-rand` only accepts floats as inputs. And yes, perhaps this is slightly outside the scope of `statsrs`! If this could be accomplished with `statsrs` and `map` (see above) then that would be interesting. Failing that, the `MultivariateNormal` crate could be interesting.

**Comment by troublescooter** [comment]
```
let x0: Vec<f64> = thread_rng().sample_iter(Standard).take(200).collect();

let variance: f64 =
  (SIGMA.pow(2) as f64 /  (1.0 - (-1.0).exp())).sqrt();

let normals: Vec<_> = x0
  .iter()
  .map(|&x| Normal::new(x * (-0.5).exp(), variance).unwrap())
  .collect();

```
Does this help?

I think you're expecting a different programming model coming from Python. Rust is more explicit, and functions cannot currently be overloaded based on the type of the arguments. There are some hacks to get around this, but they are rather atypical.

I'm not sure if you mistyped, I was referring to the type `MultivariateNormal` in this crate. Yes, picking a scalar covariance matrix would work. Although I've not tested whether the `nalgebra` matrices can be pushed like that, given they aren't sparse.

**Comment by vks** [comment]
We have a multivariate normal distribution now, which supports this use case.
