### ISSUE TITLE
Release request

### ISSUE THREAD

**Issue by nlhepler** [statrs-dev/statrs#138]
Hello! This is a (hopefully) polite request to check if statrs is in a state ready to have a release cut? It's been 10mo according to crates.io and I for one am eager to get off rand 0.7. Thanks again for all your hard work!

**Comment by vks** [comment]
I think only @boxtown can make a new release?

**Comment by boxtown** [comment]
@vks and @troublescooter I've moved ownership of the repo to a new @statrs-dev/owners team which I've invited you two to be on.

This should allow you to publish new releases without me. Let me know if there are any issues thanks

**Comment by vks** [comment]
Thanks, @boxtown! I opened #140 for coordinating the release.

**Comment by troublescooter** [comment]
Does @boxtown have to invite me over at crates.io in order for me to be able to publish the release there?

**Comment by vks** [comment]
I think this can be closed now.

**Comment by nlhepler** [comment]
Many Thanks!!! I'll close.

**Comment by troublescooter** [comment]
Nevermind, my first go at publishing a crate.
[v0.14](https://crates.io/crates/statrs) is up
