### ISSUE TITLE
Update to nalgebra 0.27.1 to avoid RUSTSEC-2021-0070 

### ISSUE THREAD

**Issue by nnethercote** [statrs-dev/statrs#141]
statrs's latest version is 0.14.0. (Even though the [website](https://github.com/statrs-dev/statrs) says it is 0.13.0, in the README.md and the link to the docs in the "About" section at the top right.)

statrs 0.14.0 depends on nalgebra 0.26. nalgebra has a [RUSTSEC-2021-0070 advisory](https://rustsec.org/advisories/RUSTSEC-2021-0070.html) against it. Among other things, this causes `cargo deny` to fail.

Version 0.27.1 of nalgebra fixes the advisory.

It would be very helpful if statrs could have its dependency on nalgebra updated to 0.27.1, and then a new version of statrs (0.14.1 or 0.15.0) be released. Thank you.

**Comment by vks** [comment]
Was the fix backported to nalgebra 0.26? If no, this will be a breaking change, and we will have to release statrs 0.15 to fix it, because nalgebra is part of the public interface.

**Comment by vks** [comment]
@troublescooter Should we already release 0.15?

**Comment by nnethercote** [comment]
Thank you for the fast response. As far as I can tell, the fix has not been backported to nalgebra 0.26. The most recent 0.26 release is 0.26.2, which was released on April 27. 0.27.0 was released on June 2, and 0.27.1 was released on June 4. (The exact dates may vary slightly depending on your timezone.) The advisory is dated June 6.

**Comment by nnethercote** [comment]
A 0.15 release would be great. This issue has been closed because of #142, but until there's a new release the problem hasn't been fully addressed in a way that is useful to ordinary statrs users.

**Comment by troublescooter** [comment]
Thanks for the ping, 0.15 is now up.

**Comment by nnethercote** [comment]
Thank you! I see 0.15 is present on crates.io, docs.rs, and it is named in the README. But some of the GitHub widgets still show 0.14 and 0.13:

<img width="321" alt="Screen Shot 2021-07-01 at 8 31 23 am" src="https://user-images.githubusercontent.com/1940286/124039813-fea93500-da46-11eb-8b11-2c87608f34d3.png">

I'm not sure why that is.

**Comment by troublescooter** [comment]
The doc link was in the Cargo.toml and releases track the tags/releases done on Github. I don't know about the crates.io widget, the rest is now fixed. Thanks!

**Comment by vks** [comment]
> I don't know about the crates.io widget, the rest is now fixed.

I guess we have to wait until shields.io updates the image.
