### ISSUE TITLE
I wonder why there is no "median" function for rust array?

### ISSUE THREAD

**Issue by dbsxdbsx** [statrs-dev/statrs#148]
I saw  trait `median` , but not for rust array. Is there some reason for it?

I've checked  (maybe) related issue : https://github.com/statrs-dev/statrs/issues/3;  https://github.com/statrs-dev/statrs/issues/15

**Comment by vks** [comment]
This is a library for statistical distributions, so things are framed a bit differently than in an array library. If you want to calculate the median of an array, you have to create a [`Data`](https://docs.rs/statrs/0.15.0/statrs/statistics/struct.Data.html) distribution first. Then, you can calculate the median, like [here](https://docs.rs/statrs/0.15.0/statrs/statistics/struct.Data.html#impl-Median%3Cf64%3E).

**Comment by YeungOnion** [comment]
Hope the advice from @vks provided direction, closing.
