### ISSUE TITLE
Is statrs::distribution::Laplace correct?

### ISSUE THREAD

**Issue by vi** [statrs-dev/statrs#150]
Assuming it is [this Laplace distribution](https://en.wikipedia.org/wiki/Laplace_distribution), generated samples look strangely distributed:

![q](https://user-images.githubusercontent.com/173219/130338534-89b31e57-e862-4555-b7ca-1cf0d8e134d8.png)

Wikipedia shows symmetric density function, but all values generated by `statrs::distribution::Laplace` are positibe (assuming zero `location` parameter).

[Formula](https://github.com/statrs-dev/statrs/commit/fd3a447cd02ef031a58cf086fe9a703357026644#diff-fe4427f3325a5e2ecbd8bfefe46c9a542af8404013fdca6377ce2e83ed7345deR85) used in the code reuses uniform float value both as sign and as exponential distribution generator, but actually has no way to ever generate negative values.

**Comment by boxtown** [comment]
Looks like there's a bug [here](https://github.com/statrs-dev/statrs/blob/master/src/distribution/laplace.rs#L85)

Should be

```Rust
self.location - self.scale * x.signum() * (1.0 - 2.0 * x.abs()).ln()
```

**Comment by vi** [comment]
@boxtown Are you going to submit a pull request for this?
