### ISSUE TITLE
StudentsT inverse_cdf is broken

### ISSUE THREAD

**Issue by scullionw** [statrs-dev/statrs#156]
It is currently only valid for ranges .25-0.5 and .75-1, which is probably why the tests don't catch it.

```rust
use statrs::distribution::{ContinuousCDF, StudentsT};

fn t_ppf(q: f64, freedom: f64, location: f64, scale: f64) -> f64 {
    StudentsT::new(location, scale, freedom)
        .unwrap()
        .inverse_cdf(q)
}

fn main() {
    let mut x = 0.01;

    while x < 1.0 {
        let y = t_ppf(x, 2.74, 0.0, 1.0);
        debug_plotter::plot!((x, y));
        x += 0.01
    }
}
```

![src-main rs:14:9](https://user-images.githubusercontent.com/11668344/143498378-8bac5f1b-35a0-4f0f-9e8b-4c9b675baf6c.png)

it should look like this:

<img width="502" alt="Screen Shot 2021-11-25 at 3 48 12 PM" src="https://user-images.githubusercontent.com/11668344/143498597-3e98c805-3bdd-4646-a23c-d49753629832.png">

I currently fix it in my code with

```rust
fn t_ppf(q: f64, freedom: f64, location: f64, scale: f64) -> f64 {
    let candidate = StudentsT::new(location, scale, freedom)
        .unwrap()
        .inverse_cdf(q);

    if q < 0.25 {
        candidate * -1.0
    } else if q < 0.5 {
        candidate
    } else if q < 0.75 {
        candidate * -1.0
    } else {
        candidate
    }
}
```

**Comment by WarrenWeckesser** [comment]
I create a pull request with a fix: https://github.com/statrs-dev/statrs/pull/159.
