### ISSUE TITLE
Calculate the coefficient of variation without calculating the mean twice?

### ISSUE THREAD

**Issue by Boscop** [statrs-dev/statrs#175]
With this crate, is it possible to calculate the [coefficient of variation / relative std dev](https://en.wikipedia.org/wiki/Coefficient_of_variation#:~:text=The%20coefficient%20of%20variation%20(CV)%20is%20defined%20as%20the%20ratio,the%20mean%20of%20the%20population.) (`data.std_dev()/data.mean()`) without calculating the mean twice?

**Comment by YeungOnion** [comment]
If the distribution is specified by a family of distributions, e.g. Normal, Exponential, then it certainly won't need to be computed twice. 

If however, you need to determine this from data, perhaps from an iterable, then the Empirical distribution's implementation `add` to add a datum will stream the variance and mean.

[`average`](https://crates.io/crates/average) may also be useful for you.

**Comment by YeungOnion** [comment]
Closing for now, but this kind of question does motivate having a discussion space.
