### ISSUE TITLE
Example code contains errors

### ISSUE THREAD

**Issue by EliaBernardi** [statrs-dev/statrs#181]
I am struggling with MultivariateNormal creation.
I read the documentation [https://docs.rs/statrs/0.13.0/statrs/distribution/struct.MultivariateNormal.html](url) and tried to copy and paste the example code, but it won't compile because it contains errors.

I'm using 
statrs = "0.16.0"
nalgebra = "0.32.1"

even though I tried with many different version of the libraries (suggested by the error) I can't make it work.

**Comment by eliabernardi01** [comment]
This code works 
<pre><code>
let mvn = MultivariateNormal::new(vec![0., 0.], vec![1., 0., 0., 1.]).unwrap();
let a =  DVector::from(vec![1.,1.]);
println!("PDF : {:?}",mvn.pdf(&a));
</code></pre>

These versions of the libraries make the code works:
statrs = "0.14.0"
nalgebra = "0.26.2"

**Comment by YeungOnion** [comment]
I think it would be good to document that the API for MultivariateNormal introduces a public dependency for `nalgebra::DVector`, but would you consider this issue fixed?

**Comment by YeungOnion** [comment]
closing for now, started discussing this issue and related in broader scope in #225
