### ISSUE TITLE
Inverse CDF for binomial distribution doesn't seem to converge

### ISSUE THREAD

**Issue by derekdreery** [statrs-dev/statrs#185]
It currently falls back to what looks like interval bisection, but it then doesn't seem to converge, which is strange since the inverse cdf is monotonic IIUC.

**Comment by troublescooter** [comment]
Can you provide parameters that do not converge?

**Comment by derekdreery** [comment]
Hi sorry yes I should have given more information. The one I'm using is `Binomial::new(0.018, 465).inverse_cdf(0.0003472)`. In the function itself, the lower bound settles on `0` while the upper bound settles on `1`.

**Comment by derekdreery** [comment]
According to `R`, the correct answer is `1`.

**Comment by ImJeremyHe** [comment]
Don't converge here
```rs
#[cfg(test)]
mod tests {
    use statrs::distribution::{Binomial, DiscreteCDF};

    #[ignore]
    #[test]
    fn binomial() {
        let result = Binomial::new(0.5, 6).unwrap().inverse_cdf(0.75);
        assert_eq!(result, 6);
    }
}
```

**Comment by YeungOnion** [comment]
Took a look and submitted a PR. Thanks all, please provide me feedback there.

**Comment by ImJeremyHe** [comment]
@YeungOnion Really thanks for your work! Would you mind releasing a new version?

**Comment by YeungOnion** [comment]
Sure, a fix release would be a good way for me to make the minor release smooth too. Source is now on branch `fix-issue-185` but I'm having issues publishing.

---

@statrs-dev/owners do any of you have publish access to crates.io or can here help? I get a 403 error when I run `cargo publish`
```text
~/p/statrs @8b1439e 25.5s ❱ cargo publish
    Updating crates.io index
   Packaging statrs v0.16.1 (/home/orion/projects/statrs)
   ... # truncated
   Compiling statrs v0.16.1 (/home/orion/projects/statrs/target/package/statrs-0.16.1)
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 26.21s
    Packaged 63 files, 686.0KiB (133.6KiB compressed)
   Uploading statrs v0.16.1 (/home/orion/projects/statrs)
error: failed to publish to registry at https://crates.io

Caused by:
  the remote server responded with an error (status 403 Forbidden): this crate exists but you don't seem to be an owner. If you believe this is a mistake, perhaps you need to accept an invitation to be an owner before publishing.
```

Things I've noted that I've [read (from cargo docs)](https://doc.rust-lang.org/cargo/reference/publishing.html) are required
- I'm in the statrs-owners group and crates.io has that github group in there, per `cargo owner -l`
- third-party access to the GitHub group is approved for crates.io
- I've signed into crates.io with this GitHub account and crates.io is an authorized OAuth app on this account.

Anything I might be missing?

**Comment by boxtown** [comment]
I think (confusingly) there's a [statrs-dev/owners](https://github.com/orgs/statrs-dev/teams/owners/members) team that you were not a part of (despite having owners for the org). I believe the team is what has publish rights to the crate.

I just added you to the owners team, please let me know if this helps resolve the issue :)

**Comment by YeungOnion** [comment]
The auth worked, thanks!

@ImJeremyHe I forgot to also update the version in the README which still reads "0.15.0", but this fix is in.
