### ISSUE TITLE
nalgebra v0.27 (dependency of statrs) is going to get rejected by a future version of rust

### ISSUE THREAD

**Issue by robinpaul85** [statrs-dev/statrs#188]
One of the dependencies of statrs, nalgebra v0.27.1 is going to be rejected by a future version of rust. Can you please use a more recent version of nalgebra?

With cargo version 1.68.0, I am getting the following message:

warning: the following packages contain code that will be rejected by a future version of Rust: nalgebra v0.27.1

**Comment by y9c** [comment]
https://github.com/statrs-dev/statrs/pull/187

This RP might fix it

**Comment by YeungOnion** [comment]
#187 was merged, closing
