### ISSUE TITLE
Is the crate/protect still maintained/alive?

### ISSUE THREAD

**Issue by Magnetuz** [statrs-dev/statrs#201]
I noticed that the latest commit to main is from September 2022. Many old PRs and still opened.

Is this project/crate still maintained or alive?

Thanks

**Comment by YeungOnion** [comment]
I saw that the owner has had effectively zero activity on GitHub in the past two years, seems like we need a fork and a maintainer if we like this enough.

**Comment by dhardy** [comment]
I could host under https://github.com/rust-random/ if need be, but have no intention of maintaining the crate myself. (The only point is that I could approve other maintainers as they step up.)

**Comment by YeungOnion** [comment]
That would be nice, but perhaps this should wait until someone can actually step in as a maintainer.

While I'm willing, I have zero experience and feel _really_ underqualified - I'm not even hired as a junior developer yet. @dhardy if you'd be alright being (or connecting me to) a mentor that's not a maintainer while I'm a maintainer, then I'll operate as a first pass filter. If you don't have that bandwidth or don't know someone who's willing to, I won't go for it.

**Comment by dhardy** [comment]
@YeungOnion sure, I can provide some mentorship. If you're not in a hurry, lets wait at least until next week to see if anyone else has something to say.

The [crate](https://crates.io/crates/statrs) is owned by @boxtown and [statsrs-dev](https://github.com/orgs/statrs-dev/people)... but I don't see anyone there (or know of hidden members).

**Comment by tessob** [comment]
@dhardy I think it is a good idea to fork the repo and develop it further. If @boxtown will come back we will find a way to merge all together.

Anyway a new maintainer need to fix the situation with tests. When I committed my pool request it was not clear how to run all tests. So, on my opinion, `cargo test` command should work before a new crate will be published on `crates.io`. I believe this is a minimal and fair threshold criteria for a fork.

**Comment by vks** [comment]
@dhardy Me and @troublescooter are members, but I think we cannot add anyone else.

**Comment by Magnetuz** [comment]
Hey @boxtown, thank you! Your assistance is very appreciated 👍🏻

**Comment by tessob** [comment]
@Magnetuz [this one](https://github.com/statrs-dev/statrs/pull/190). Half year ago, it wasn't very clear to me how to deal with it.

**Comment by henryjac** [comment]
I would be willing to help maintain this crate, perhaps in collaboration with @YeungOnion. I have no prior experience with maintaining but have submitted some PRs for this crate. Will be able to find help within my organisation for learning best practices etc.

Seeing this also made me fix tests in the old PRs and refresh my knowledge of the crate. Excited to see this get going again!

**Comment by boxtown** [comment]
@henryjac and @YeungOnion I've invited both of you to the statrs-dev org as owners. I believe this should allow you to publish/yank crates as well.

If and when you feel comfortable, I can add one or both of you as named owners of the crate (and potentially remove myself).

Thanks a bunch for stepping up! I genuinely wished I had the time/drive to give this crate the attention it deserves but I'm happy to see it transition to people who are interested in the maintaining health of the project. Best of luck!

**Comment by YeungOnion** [comment]
@Magnetuz thanks for posting the issue, it really took off quite well. 

@boxtown thanks for checking in and helping us out with this transition, best wishes for what your journey has in store for you. 

@henryjac guess we're a team now! I'll be doing some reading on what to know as a new maintainer, and I'll reach out within 48 hours.

@dhardy I deeply appreciate your offer to mentor me and if that's still on the table I'll gladly accept.

**Comment by dhardy** [comment]
@YeungOnion give me a ping if you have questions; I don't keep a close eye on this repository.

**Comment by YeungOnion** [comment]
While @henryjac and I want a place to discuss how we'll be functioning as maintainers, I believe the answer to the question this issue asks is _yes_.

**Comment by wangjiawen2013** [comment]
Glad to hear that this project is alive !
