### ISSUE TITLE
review CI

### ISSUE THREAD

**Issue by YeungOnion** [statrs-dev/statrs#207]
Since it's been some time, let us ensure that our CI is as useful as we need it to be.

A few ideas I think would be useful beyond running our tests,
- running clippy
- generally fail on rustc warnings
- dependabot
- cross-platform

**Comment by FreezyLemon** [comment]
I've recently set up CI workflows for some other Rust projects, so I could take a look at this if you're not working on it already.

Do you want a job running for all three major platforms (windows, macos, linux)? AFAICT, the project doesn't really have any platform-specific code. On the other hand, it's not that hard to set up..

**Comment by YeungOnion** [comment]
I think that'd be great, thanks!

**Comment by YeungOnion** [comment]
> * running clippy
> * generally fail on rustc warnings
> * dependabot
> * cross-platform

clippy, fail on warn, and cross-platform by @FreezyLemon in #215 
dependabot by @YeungOnion in #238
