### ISSUE TITLE
Bug: Mode calculation for Gamma distribution

### ISSUE THREAD

**Issue by tessob** [statrs-dev/statrs#210]
Gamma distribution with the following parametrization:
```rust
Gamma::new(0.2422859569300416, 0.0000033637229958478293)
```
produces really weird mode value – `Some(-225260.53542615683)`.

[In Wolfram there is no mode for this distribution](https://www.wolframalpha.com/input?i=GammaDistribution%5B0.2422859569300416%2C+1%2F0.0000033637229958478293%5D)

**Comment by YeungOnion** [comment]
resolved by #212
