### ISSUE TITLE
Support MSRV concept

### ISSUE THREAD

**Issue by YeungOnion** [statrs-dev/statrs#242]
We tried this out for the #235, but ran into some trouble when dev-dependencies were not able to satisfy the version that the lib can. Since it's not tested while on crates.io, perhaps this is a non-issue, but it does mean that the CI will fail because of dependencies that we currently use for benchmarking. It would be nice to ensure that the tests will run on our MSRV. Any other input welcome here regarding what one would expect of the MSRV information and what might be unexpected or where you would expect to look for information if something isn't going your way when using this dependency.

**Comment by FreezyLemon** [comment]
Is there a target for the level of backwards compatibility? The concept of a MSRV has been discussed before, but the actual minimum version that should be supported has not been, I don't think.

I'll give you some examples to illustrate what I mean (these are "targets" I've seen in other projects before):
- Support all `rustc` versions that are shipped by the Ubuntu LTS repositories (or another distro)
- Support the current rustc stable and X versions before it
- Support the last X months of rustc stable releases
- Don't target anything, just use MSRV to *inform* users what is supported, change MSRV whenever needed or wanted

All of these have pros and cons. I personally would tend towards not going too far with backwards compatibility as it causes a significant maintenance burden the further you go (and not being able to use new language features is no fun).

**Comment by YeungOnion** [comment]
At the moment, I'm leaning toward the least stringent which is the last option,

> Don't target anything, just use MSRV to _inform_ users what is supported, change MSRV whenever needed or wanted

On the basis that there's not a large usage volume of this crate, and I think knowing more about the breadth of use for this library would be helpful.

**Comment by FreezyLemon** [comment]
I honestly agree, it's the simplest option and unless there's an explicit request for more backwards compatibility, it probably doesn't make sense to overthink it.

**Comment by YeungOnion** [comment]
Yeah, seems like a good approach for now. Glad for your putting a light on it so it's intentional.
